### ISSUE TITLE
unexpected exception "Integration is invalid, according to hassfest"

### ISSUE THREAD

**Issue by jugla** [KTibow/ha-blueprint#16]
When running combined.yaml, it fails
[https://github.com/jugla/KeyAtome/actions/runs/1624891154](url)

I got the following error : 
`
Run KTibow/ha-blueprint@stable
Run # Installation
Installing dependencies.
Collecting colorama
  Downloading colorama-0.4.4-py2.py3-none-any.whl (16 kB)
Installing collected packages: colorama
Successfully installed colorama-0.4.4
Hassfest setup
Flake8 setup
Format setup
No JS files found, not installing eslint and prettier.
Run # Validation
Hassfest
  /entrypoint.sh: line 11: integrations: unbound variable
  Traceback (most recent call last):
    File "/home/runner/work/_actions/KTibow/ha-blueprint/stable/validate_code.py", line 25, in <module>
      raise Exception("Integration is invalid, according to hassfest")
  Exception: Integration is invalid, according to hassfest
  Error: Process completed with exit code 1.
`

**Comment by KTibow** [comment]
This action is old. I'm going to try to make it again from scratch now.

**Comment by KTibow** [comment]
Actually no I'm too lazy, just manually use hassfest and HACS on their own

**Comment by jugla** [comment]
Thanks.
I've done it.

**Comment by KTibow** [comment]
Added a warning to the action that it's old. Glad you could figure it out own your own.
